- spatialmath/base/transforms3d.py
Dear @petercorke, 
here is mentioned pull request.  
HINT: The issue arises whenever the passed pose T in SE3 is not in the origin @ [0;0;0] and the argument length != 1.
The reason is that the length is not just defining the length of the unit-vector in the x,y,z-direction in that pose,
but it is scaling the whole transformation matrix.
x = TF * vec * s   // TF is a 4x4 homogeneous transformation matrix in SE3, vec is a 4x1 homogeneous vector and s is a scalar
// can be rewritten as 
x = TF * s * vec  // now it should be clear  that multiplying a TF with a scalar leads to a non-SE3 element. 
One can also argue that,  vec * s does not result in a homogeneous vector either. 
I hope that was enough explanation :) 
My solution was already mention in the previous PR: …
> [FIX] base.trplot(): argument length was scaling hom. tf

- spatialmath/quaternion.py
The `vec` and `vec_xyzs` fields of the `Quaternion` class currently return the same 4-vector (s, x, y, z).
This pull request updates `vec_xyzs` to return (x, y, z, s).
> Fix implementation of Quaternion.vec_xyzs

- spatialmath/pose3d.py
Fixing an issue where passing check=False to SE3.Rt still results in invalid constructor errors for certain rotation matrices.
> Fixing issue with SE3.Rt ignoring check=False

- spatialmath/base/transforms2d.py
I found an error in trplot2()
The code below reproduces the error
```python
a = SE2.Rand()
a.plot(length=0.1)
```
This is because the code below breaks the homogeneous form.
```python
o = T @ np.array([0, 0, 1])
x = T @ np.array([1, 0, 1]) * length	
y = T @ np.array([0, 1, 1]) * length
```
So, I modified it in a similar way to trplot().
```python
o = T @ np.array([0, 0, 1])
x = T @ np.array([length, 0, 1])
y = T @ np.array([0, length, 1])
```
> fix trplot2 length argument error

- spatialmath/baseposematrix.py
This PR has two parts.
**1. Error in `!=` comparisons**
Comparing two of most things using the `!=` operator currently fails with the following error unless you make them lists:
```
In [6]: SO3() != SO3()   
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-16fbcbbd9d14> in <module>
----> 1 SO3() != SO3()
~/qut/repos/spatialmath-python/spatialmath/baseposematrix.py in __ne__(left, right)
1560 
1561         """
-> 1562         return [not x for x in left == right]
1563 
1564     def _op2(
TypeError: 'bool' object is not iterable
```
This is due to `__ne__` assuming comparison results are a list. Commit 13d6ee1 addresses this.
**2. An _opinionated_ change to `==` …
> Fix __ne__ error, and add opinionated change to __eq__, in `BasePoseMatrix`

- spatialmath/twist.py
Calling Twist3.Rx(0.5) results in a TypeError: 'float' object is not iterable error. The same error is experienced for Twist.Ry and Twist.Rz as well.
This change converts the output of base.getunit to a vector if a scalar value is provided for theta.
> Fixing crashing bug when using Twist3.R[x,y,z]

- spatialmath/twist.py
Division by a scalar works for `Twist3` classes, but throws this error for `Twist2` classes:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-05a7052c8927> in <module>
----> 1 t / 1                                                                                        
~/qut/repos/spatialmath-python/spatialmath/twist.py in __truediv__(left, right)
283     def __truediv__(left, right):  # lgtm[py/not-named-self] pylint: disable=no-self-argument
284         if base.isscalar(right):                                                             
--> 285             return Twist3(left.S / right)                                                    
286         else: …
```
> Fix division by scalar for `Twist2` classes

- spatialmath/base/transforms3d.py
Hi @petercorke,
Many thanks for developing this wonderful package!
As mentioned in https://github.com/petercorke/spatialmath-python/issues/52#issuecomment-1135414149, I found that the following import behavior does not work in Python 3.6 due to circular imports (but works in 3.7+, which is mentioned in https://github.com/python/cpython/issues/74210):
https://github.com/petercorke/spatialmath-python/blob/da5aa910617869715da9e661da475ba83b28c59f/spatialmath/base/transforms3d.py#L24
Therefore, I manage to fix this issue by simply modifying the statement to let the project work fine in Python 3.6 as well.
Please let me know if you have any questions or comments for this pull request. Thank you!
Best,
Yu-Kai
> Fixes import errors in Python 3.6 #52

- spatialmath/base/transforms3d.py
When plotting with arrow style but assigning different colors to each axis, then there is a color mismatch.
```
X = SE3.Rand()
X.plot(color=["r","g","b"], textcolor="k")
```
One would expect color-wise:
`X.plot(color=["r","g","b"], textcolor="k", style="line")`
Investigation of the code revealed that there was an indexing error when plotting the x-axis with quiver.
> Fix color of arrow style

- spatialmath/base/transforms3d.py
According to the description, the color for origin and axis labels should default to `color`. However,
- if origin color is defined without a frame label, then origin color is ignored
- if a frame label is given, then the color is set to blue for origin and axis labels
```
X = SE3.Rand()
X.plot(color=["r","g","b"], textcolor="k", origincolor="k", style="line")
```
`X.plot(frame="A", color=["r","g","b"], textcolor="k", origincolor="k", style="line")`
There was some "code duplication".
> Fix handling of color for labels

- spatialmath/pose3d.py
- tests/test_pose3d.py
There is functionality to "lift" an SE2 object to an SE3 object. This adds the ability to "flatten" an SE3 object to SE2. It is useful for some of the workflows at BDAI. 
I added a unit test for this.
> Add "flattening" from SE3 to SE2.

- pyproject.toml
- spatialmath/pose3d.py
- tests/test_pose3d.py
Decided not to assign default args in the event of something like (x, y) being passed in because default values aren't specified
> [SW-237] Raises error if a number of arguments besides 1 and 3 are passed in to SE3 constructors

- spatialmath/base/transforms3d.py
- tests/test_pose3d.py
Found an error when using the log map on near identy rotations. This was cause by slight inaccuracies in the conversion resulting in a trace of 3 + eps, which results in a value > 1 being passed to acos in the log map function. Added a min between the value and 1 to fix this as well as unit tests. 
``
from spatialmath import  SO3
R = SO3.Rand()
R_test = (R.inv() * R)
print((R.inv() * R).eulervec())
``
> Fixed domain errors in acos near identity

- spatialmath/quaternion.py
- tests/test_quaternion.py
Previously, passing an invalid rotation matrix to the `UnitQuaternion` constructor would just silently fail and yield an identity quaternion. For example:
```python
>>> R = 1.1 * np.eye(3)  # not a valid rotation matrix
>>> UnitQuaternion(R)
1.0000 <<  0.0000,  0.0000,  0.0000 >>
```
Funnily enough, this only happens when `check=True`, since when `check=False` the constructor assumes it can try to interpret the argument as a quaternion (i.e., a vector of length 4) and fails.
This PR fixes this problem by adding additional checks against the argument passed to the constructor, and also has a specific check for when the matrix passed is 3x3 but is not a valid rotation matrix.
> Raise error on invalid rotation matrix in UnitQuaternion constructor.

- spatialmath/base/transforms3d.py
- tests/test_transforms3d.py
This is hopefully a simple fix to pass only the check flag from tr2angvec to its children function. If other people need to be on this PR let me know.
> [N/A] Check fix for eulervec and tr2angvec

- spatialmath/base/__init__.py
- spatialmath/base/transforms2d.py
- spatialmath/base/transforms3d.py
- spatialmath/base/vectors.py
- tests/base/test_transforms2d.py
- tests/base/test_transforms3d.py
- tests/base/test_vectors.py
fix the problem with angdiff, ndarray output for two scalar inputs.  Issue #81.  Also updated the tests.  Note that the equality tests from `unittest` and `numpy.test` consider that a single element array is equal to a scalar.  Now added explicit tests for type of result.
> ensure that angdiff returns a scalar for scalar args

- tests/base/test_graphics.py
- tests/base/test_transforms2d.py
- tests/base/test_transforms3d_plot.py
- tests/test_geom2d.py
- tests/test_geom3d.py
- tests/test_pose2d.py
- tests/test_pose3d.py
Update several unit tests' `skipif` conditions, as a follow-up to https://github.com/bdaiinstitute/spatialmath-python/pull/96
- background: tkinter issue on mac https://github.com/actions/setup-python/issues/649
Some example traces taken from the build-test workflow for this PR:
- [(mac-latestos, 3.11)](https://github.com/bdaiinstitute/spatialmath-python/actions/runs/6935373975/job/18865396757?pr=102): `tests/base/test_graphics.py .............`
- [(mac-latestos, 3.7)](https://github.com/bdaiinstitute/spatialmath-python/actions/runs/6935373975/job/18865395394?pr=102): `tests/base/test_graphics.py sssssssssssss`
> [SW-562] update unit test skipif condition for mac-related issues

- spatialmath/base/transforms3d.py
This PR is part of the effort to improve consistency of tolerance usages in various checks (e.g. `ishom`, `isR`, etc.), it fixes a couple of simple issues where the `tol(erance)` is set but not passed to sub-routines.
> pass tolerance value when calling sub-routines

- spatialmath/base/quaternions.py
- spatialmath/base/transforms2d.py
- spatialmath/base/transforms3d.py
- spatialmath/base/transformsNd.py
- spatialmath/base/vectors.py
- spatialmath/baseposematrix.py
- spatialmath/geom2d.py
- spatialmath/geom3d.py
Update additional cases of `tol(erance)` usages in code.  As an intial pass, this PR only ensures that tolerance, when provided, should be passed to sub-routine when applicable.
In a follow-up, the default values and some tolerance implementation details may also be standardized.
> Standardizing tolerance uses

- spatialmath/base/quaternions.py
- spatialmath/base/transforms2d.py
- spatialmath/base/transforms3d.py
- spatialmath/base/vectors.py
- spatialmath/geom3d.py
- spatialmath/quaternion.py
- tests/base/test_transforms2d.py
- tests/base/test_transformsNd.py
- tests/base/test_vectors.py
- another pass by searching and checking all `_eps` usages (previously missed when searching with `tol` keyword);
- fix a few docstring issues;
- fix a minor bug in `angle_wrap`;
- improve test coverage for math methods (passing up visualization methods for now).
> Update more tolerance usages, add a few docstring and unit test

- .pre-commit-config.yaml
- README.md
- pyproject.toml
Enable black as pre-commit hook, update README with a mention of it as an optional setup step.
Early exploration showed that enabling ruff and mypy would be a slightly long term effort, beyond the scope of this task.
> Enable black as a pre-commit hook

- spatialmath/base/quaternions.py
- spatialmath/base/transforms2d.py
- spatialmath/base/transforms3d.py
- spatialmath/base/transformsNd.py
- spatialmath/base/vectors.py
- spatialmath/geom2d.py
- spatialmath/geom3d.py
- spatialmath/quaternion.py
Update the default values for `tol`(lerance) across the board, with the following justifications:
- Using the same default value should help set user expectations, particularly when combined with updated docstrings;
- If these changes break any code, it might help push the user to review previous assumptions of numerical tolerances in the context of the actual use case.
> Use same tol defaul values

- README.md
- spatialmath/quaternion.py
- tests/test_quaternion.py
This is a first pass for the task "Bounds on acos and other functions with bounded domains", with focus on `acos` and `asin` usages.
- All usages of `math.acos`, `math.asin` reviewed;
- Changes included in this PR are cases with clear intention and the clampings added simply guard against floating point error (e.g. dot product of two unit quaternions should have norm <= 1).
> Bounds on acos usages; fix a couple of links in readme

- pyproject.toml
According to https://pypi.org/project/spatialmath-python/#history, the new release version should be > 1.1.8.
> Update pyproject.toml version based on pypi release history

- spatialmath/baseposematrix.py
- tests/test_pose3d.py
Fixes fall through error in the binary operator for BasePoseMatrix described in #116:
https://github.com/bdaiinstitute/spatialmath-python/blob/1b89c49395a21b5241e2f0a233e69394f3bc27b1/spatialmath/baseposematrix.py#L1632C7-L1632C7
If you want to compare the rotation of an SE3 to an SO3, it returns `None` as opposed to throwing an error or returning a valid value.
```
import numpy as np
from spatialmath import SE3, SO3
T0 = SE3()
print(T0.angdist(SO3()))
```
Modified `BasePoseMatrix._op2` to throw an error if the types don't match. 
All tests still pass.
> Fixed fall through error in binary operation

- spatialmath/quaternion.py
- tests/test_quaternion.py
Add code+test to make sure using 4x1 vector with v keyword argument in UnitQuaternion works.
> Fix UnitQuaternion constructor with v keyword.

- docs/source/intro.rst
- Fixed code example bugs (~ Ln. 214 and ~Ln. 614)
- ``T`` was not defined; 
- ``quat.qqmul`` -> ``qqmul``
- Clarified sentence at Ln. 156.
> Fixed code block bugs and clarified a sentence in intro.rst

- spatialmath/__init__.py
- spatialmath/base/animate.py
- spatialmath/spline.py
- tests/test_spline.py
This adds a class to represent SE3 trajectories using a b-spline (using scipy's b-spline class under the hood). A small example is included, with a visualization.
Fixes a minor bug with the animation functionality.
> Add BSplineSE3 class.

- spatialmath/base/graphics.py
- tests/base/test_symbolic.py
Fixes several issues that broke the testing workflow:
- a few assertEqual cases in tests, uses math.isclose for float values;
- a case where call to matplotlib's `add_collection3d` now requires items in `_segments3d` to have homogeneous shapes (breaking change introduced by matplotlib and numpy).
> Fixes several issues that broke the testing workflow

- spatialmath/base/animate.py
- spatialmath/base/transforms2d.py
- spatialmath/base/transforms3d.py
Fix several issues related to #126 
- expose "ax" and "dims" arguments to animate(...), to be consistent with other API's;
- update animate implementation to be consistent with trajectory frame's data type, in particular, SE3Array / SO3Array types instead of SE3 / SO3, in line with animate.run(...)'s implementation.
Example use-cases:
```
...
ax = fig.add_subplot(111, projection='3d')
T1.plot(ax=ax, dims=[-5, 10])
T1.animate(start=T2, ax=ax)  # would use the existing ax which is [-5, 10]
plt.show()
```
> [Issue-126] fix several issues with animate

- .github/workflows/master.yml
- pyproject.toml
Pin matplotlib version in pyproject.toml so that the installation won’t cause issue in ROS2 setups where matplotlib has been apt-installed and hence pinned to version 3.5.1. This particular version pinning also results in a narrower numpy version range "numpy>=1.22,<2" and an end of support for python 3.7.
This PR is a WIP.
Tests done:
- ubuntu + python 3.7, windows + python 3.7 (numpy does not have a version for this env);
- windows + python 3.11, windows + python 3.12 (matplotlib does not provide a wheel for this env);
NOTE: the other part of the discussion, i.e. the matplotlib related imports should better be confined to sub modules where plotting is actually needed, is not resolved by this PR.
> [Issue-127] Pin version to match apt-installed python3-matplotlib

- spatialmath/spline.py
We've started getting some loud warnings about using `is` instead of `==` when checking string values.
```
/usr/local/lib/python3.10/dist-packages/spatialmath/spline.py:195: SyntaxWarning: "is" with a literal. Did you mean "=="?
if check_type is "local":
/usr/local/lib/python3.10/dist-packages/spatialmath/spline.py:202: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif check_type is "global":
```
This small PR should resolve that.
Closes #146
> Fix string equality warnings in `SplineFit` class

- .github/workflows/master.yml
- .github/workflows/publish.yml
- .github/workflows/sphinx.yml
This is simply a find/replace of `ubuntu-latest` -> `ubuntu-22.04`.  Because `ubuntu-latest` will become 24.04 soon.  We should pin to 22.04 which matches our development environment.
None. This PR is the test.  (Assuming this repo has CI)
> [SW-1712] Pin ubuntu version in workflows

- README.md
- pyproject.toml
Previously, we added version pinning by default for `matplotlib` and `numpy`, to avoid conflicts with system-installed packages in ROS2. This PR removes the default version pinning, moving to a `ros-humble` under `project.optional-dependencies` in `pyproject.toml`.
Now, to avoid version conflicts under ROS2 (Humble), the package can be installed via
```
pip install spatialmath-python[ros-humble]
```
and the `README.md` is updated to reflect this.
Tested that:
- adding `[ros-humble]` to the installation command enforces ROS-compatible library versions, avoiding conflict;
- installing without `[ros-humble]` installs up-to-date versions of the libraries.
> Optional deps humble

- spatialmath/pose3d.py
- spatialmath/quaternion.py
- tests/test_pose3d.py
- tests/test_quaternion.py
New method `mean()` for each of `SO3` and `UnitQuaternion`, computes the Karcher (rotational) mean.
Relatively straightforward for `SO3` but `UnitQuaternion` required a bunch of changes to allow more methods to handle multi-valued `UnitQuaternion` objects.  Fixed for `RPY()`, `Eul()`, `UnitQuaternion()` constructor, `log()` and `exp()`.  Also had to fix edge case for `log()` and `exp()` for the unit quaternions case.
Tests and doco updated.
The result is a lot of changes, but generally improved functionality for the `UnitQuaternion` class.
> compute mean of a set of rotations

- spatialmath/pose3d.py
- tests/test_pose3d.py
OpenCV represents poses by a pair of 3-vectors: rvec (exponential coordinates) and tvec (translation).  Two new methods: construct an SE3 from rvec, tvec, and convert SE3 to rvec, tvec.
Tests and doco included.
> Add methods to convert SE3 to/from the rvec, tvec format used by OpenCV

- spatialmath/base/__init__.py
- spatialmath/base/quaternions.py
- spatialmath/quaternion.py
- tests/base/test_quaternions.py
Add `q2str()` to convert a quaternion to a string, replacing old functionality of `qprint(..., file=None)` which is unintuitive.  Added deprecation notice to `qprint` if this type of call is invoked, but `file` can be set to any valid file-like object reference.
Tests and doco provided.
> Add `q2str` to convert quaternion to string

- docs/source/conf.py
Changed by the matplotlib project.  This source allows referencing of `matplotlib` classes and methods from spatial math doco.
> Fix the intersphinx source for matplotlib.

- .pre-commit-config.yaml
- docs/source/conf.py
- pyproject.toml
- spatialmath/DualQuaternion.py
- spatialmath/__init__.py
- spatialmath/base/animate.py
- spatialmath/base/quaternions.py
- spatialmath/base/transforms2d.py
- spatialmath/base/transforms3d.py
- spatialmath/baseposelist.py
- spatialmath/baseposematrix.py
- spatialmath/pose3d.py
- spatialmath/quaternion.py
- spatialmath/spline.py
- spatialmath/twist.py
- tests/base/test_numeric.py
- tests/base/test_symbolic.py
- tests/base/test_transforms.py
- tests/base/test_transforms2d.py
- tests/base/test_transforms3d.py
- tests/base/test_transformsNd.py
- tests/base/test_vectors.py
- tests/test_baseposelist.py
- tests/test_dualquaternion.py
- tests/test_pose3d.py
- tests/test_quaternion.py
- tests/test_spline.py
- tests/test_twist.py
Attempting to make the pre-commit hooks work with black.
> Format everything with black.

- spatialmath/base/transforms3d.py
- tests/test_pose3d.py
This commit fixes issue 165. 
It would benefit from a unit test, possibly the same one as referenced in the issue, but I haven't added that as I haven't set up testing.
> #165 use qunit in trinterp

- spatialmath/pose3d.py
- tests/test_pose3d.py
This extends the mean functionality of SO3 objects to SE3 objects with a new method `SE3.mean()`.  Rotation is averaged using the Karcher mean implemented in `SO3.mean()` and translation is averaged arithmetically.  There is no weighting implemented at this time.
Some mods to the documentation for `SO3.mean()` for consistency.
> Add `mean()` method for `SE3` objects.
